### ISSUE TITLE
Cannot build and run project

### ISSUE THREAD

**Issue by rrkotik** [chimera-suite/OntopStream#1]
Hi, for example the most recent error i've faced is missing implementation of TurtleOBDAVisitor interface. 
I managed to build with skipTests.
Also i started docker with flink and kafka from https://github.com/chimera-suite/OntopStream-running-example and trying to run ontop cli as in ontop docker with command : java -Xmx512m -cp mypath/ontopjdbc/*:mypath/ontoplib/* -Dfile.encoding=UTF-8 -Dlogging.config=mypath/logback.xml it.unibz.inf.ontop.cli.Ontop endpoint --mapping=mypath/taxiRides/taxi.obda --ontology=mypath/taxiRides/taxi.owl --properties=mypath/taxiRides/taxi.properties

The 1st error i get isOntopStream/core/model/src/main/java/it/unibz/inf/ontop/iq/transform/RSPIQTree2NativeNodeGenerator.java:6:42
java: package it.polimi.deib.sr.rsp.api.querying does not exist

I do it intellij to debug some of the issues.

**Comment by matbelcao** [comment]
Hi @rrkotik

Thank you for reporting this building issue.

I managed to specify better how to build the solution, as the `README` was not updated (I porobably didn't uploaded the version with the instructions for OntopStream).

The building problem is just that you need to use _jdk-11_ or _openjdk-1.11_

I will detail the installation steps I’ve followed on Linux yesterday (everything worked fine)

1. Download [JDK-11](http://jdk.java.net/java-se-ri/11)

2. Extract JDK and copy the files in your installation folder

```
tar -xvzf ./openjdk-11+28_linux-x64_bin.tar.gz

sudo cp -r jdk-11/ /usr/lib/jvm/
```

3. Set the env variable `JAVA_HOME` to the JDK path

```
export JAVA_HOME='/usr/lib/jvm/jdk-11'
```

Note: If you use a Java editor (i.e. I use Intellij), repeat step 3 also in the editor command-line. You can use `echo $JAVA_HOME` to check the configuration.

4. Build the release by running the `./build-release.sh` script in the main folder.
If the jdk version is set correcly, you should see a similar ouput in the terminal (after `$ java -version` and `$ ./mvnw -version` you should see `jdk 11` as version. If you see older versions, the build will fail.)

```
/usr/bin/java
$ java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-Ubuntu-0ubuntu3)
OpenJDK 64-Bit Server VM (build 11.0.12+7-Ubuntu-0ubuntu3, mixed mode, sharing)

$ ./mvnw -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/matbelcao/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-11
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-21-generic", arch: "amd64", family: "unix"

$ git --version
git version 2.32.0


=========================================
 Starting Ontop build script ... 
-----------------------------------------


=========================================
 Cleaning                                
-----------------------------------------


=========================================
 Compiling                               
-----------------------------------------


<<<SEVERAL BUILDING MESSAGES (may take some minutes)>>>


=========================================
 Done.                                   
-----------------------------------------

```

Then, you can check the outputs in the `build/distribution/` folder. (only the `ontop-cli` is supported right now, the other ones are for future developments)

I’ve also added the __[pre-built releases](https://github.com/chimera-suite/OntopStream/releases/tag/v4.0.3)__ pointers on GitHub (CLI and Docker), so that if you don’t want to change the internal code you can download the CLI tool and use it as-is without the need to compile anything.

There is also a new Troubleshooting section in the [README](https://github.com/chimera-suite/OntopStream/blob/feature/flink/README.md) showing the CLI arguments descriptions (they are the same ones of Ontop).

**Comment by matbelcao** [comment]
I have also added to the [README](https://github.com/chimera-suite/OntopStream/blob/feature/flink/README.md) a Troubleshooting section, so that the CLI arguments descriptions are available for everyone (they are the same ones of Ontop).

**Comment by rrkotik** [comment]
@matbelcao thank you very much Matteo! it was very useful!
